### StandardTransaktion
# Korrekte Transaktion einfügen
POST http://localhost:8080/api/rest/transaktion
Content-Type: application/json

{
  "username": "TRBank",
  "passwort": "passwort",
  "transaktionDTO": {
    "quellIban": "DE12345678901234500001",
    "zielIban": "DE12345678901234500901",
    "betrag": 1.56,
    "verwendungszweck": "Extern: Zinsen von der Bank"
  }
}

### InkorrekteTransaktion
# Inkorrekte Transaktion ausprobieren
POST http://localhost:8080/api/rest/transaktion
Content-Type: application/json

{
  "username": "TRBank",
  "passwort": "passwort",
  "transaktionDTO": {
    "quellIban": "DE12345678901234500001",
    "zielIban": "DE12345678901234500901",
    "betrag": -1.56,
    "verwendungszweck": "Externe Transaktion via REST"
  }
}
